# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a44a59ab500966b4c7a153872518c4ea"
name = "omnibus-pricing"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
    topics = [
    "app_subscriptions/update",
    "app/scopes_update",
    "app/uninstalled",
    "shop/update",
    "products/create",
    "products/update",
    "products/delete",
    "collections/create",
    "collections/update",
    "collections/delete",
    "discounts/create",
    "discounts/update",
    "discounts/delete"
  ]
  uri = "/api/webhooks"
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
